/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef stupa_CONSTANTS_H
#define stupa_CONSTANTS_H

#include "stupa_types.h"



class stupaConstants {
 public:
  stupaConstants();

};

extern const stupaConstants g_stupa_constants;



#endif
