/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Stupa_H
#define Stupa_H

#include <TProcessor.h>
#include "stupa_types.h"



class StupaIf {
 public:
  virtual ~StupaIf() {}
  virtual void add_document(const std::string& document_id, const std::vector<std::string> & features) = 0;
  virtual void delete_document(const std::string& document_id) = 0;
  virtual int64_t size() = 0;
  virtual void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query) = 0;
};

class StupaNull : virtual public StupaIf {
 public:
  virtual ~StupaNull() {}
  void add_document(const std::string& /* document_id */, const std::vector<std::string> & /* features */) {
    return;
  }
  void delete_document(const std::string& /* document_id */) {
    return;
  }
  int64_t size() {
    int64_t _return = 0;
    return _return;
  }
  void search(std::vector<SearchResult> & /* _return */, const int64_t /* max */, const std::vector<std::string> & /* query */) {
    return;
  }
};

class Stupa_add_document_args {
 public:

  Stupa_add_document_args() : document_id("") {
  }

  virtual ~Stupa_add_document_args() throw() {}

  std::string document_id;
  std::vector<std::string>  features;

  struct __isset {
    __isset() : document_id(false), features(false) {}
    bool document_id;
    bool features;
  } __isset;

  bool operator == (const Stupa_add_document_args & rhs) const
  {
    if (!(document_id == rhs.document_id))
      return false;
    if (!(features == rhs.features))
      return false;
    return true;
  }
  bool operator != (const Stupa_add_document_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_add_document_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_add_document_pargs {
 public:


  virtual ~Stupa_add_document_pargs() throw() {}

  const std::string* document_id;
  const std::vector<std::string> * features;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_add_document_result {
 public:

  Stupa_add_document_result() {
  }

  virtual ~Stupa_add_document_result() throw() {}


  bool operator == (const Stupa_add_document_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Stupa_add_document_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_add_document_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_add_document_presult {
 public:


  virtual ~Stupa_add_document_presult() throw() {}


  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class Stupa_delete_document_args {
 public:

  Stupa_delete_document_args() : document_id("") {
  }

  virtual ~Stupa_delete_document_args() throw() {}

  std::string document_id;

  struct __isset {
    __isset() : document_id(false) {}
    bool document_id;
  } __isset;

  bool operator == (const Stupa_delete_document_args & rhs) const
  {
    if (!(document_id == rhs.document_id))
      return false;
    return true;
  }
  bool operator != (const Stupa_delete_document_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_delete_document_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_delete_document_pargs {
 public:


  virtual ~Stupa_delete_document_pargs() throw() {}

  const std::string* document_id;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_delete_document_result {
 public:

  Stupa_delete_document_result() {
  }

  virtual ~Stupa_delete_document_result() throw() {}


  bool operator == (const Stupa_delete_document_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Stupa_delete_document_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_delete_document_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_delete_document_presult {
 public:


  virtual ~Stupa_delete_document_presult() throw() {}


  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class Stupa_size_args {
 public:

  Stupa_size_args() {
  }

  virtual ~Stupa_size_args() throw() {}


  bool operator == (const Stupa_size_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Stupa_size_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_size_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_size_pargs {
 public:


  virtual ~Stupa_size_pargs() throw() {}


  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_size_result {
 public:

  Stupa_size_result() : success(0) {
  }

  virtual ~Stupa_size_result() throw() {}

  int64_t success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const Stupa_size_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Stupa_size_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_size_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_size_presult {
 public:


  virtual ~Stupa_size_presult() throw() {}

  int64_t* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class Stupa_search_args {
 public:

  Stupa_search_args() : max(0) {
  }

  virtual ~Stupa_search_args() throw() {}

  int64_t max;
  std::vector<std::string>  query;

  struct __isset {
    __isset() : max(false), query(false) {}
    bool max;
    bool query;
  } __isset;

  bool operator == (const Stupa_search_args & rhs) const
  {
    if (!(max == rhs.max))
      return false;
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const Stupa_search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_search_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_search_pargs {
 public:


  virtual ~Stupa_search_pargs() throw() {}

  const int64_t* max;
  const std::vector<std::string> * query;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_search_result {
 public:

  Stupa_search_result() {
  }

  virtual ~Stupa_search_result() throw() {}

  std::vector<SearchResult>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const Stupa_search_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Stupa_search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Stupa_search_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class Stupa_search_presult {
 public:


  virtual ~Stupa_search_presult() throw() {}

  std::vector<SearchResult> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaClient : virtual public StupaIf {
 public:
  StupaClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  StupaClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void add_document(const std::string& document_id, const std::vector<std::string> & features);
  void send_add_document(const std::string& document_id, const std::vector<std::string> & features);
  void recv_add_document();
  void delete_document(const std::string& document_id);
  void send_delete_document(const std::string& document_id);
  void recv_delete_document();
  int64_t size();
  void send_size();
  int64_t recv_size();
  void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query);
  void send_search(const int64_t max, const std::vector<std::string> & query);
  void recv_search(std::vector<SearchResult> & _return);
 protected:
  boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot_;
  apache::thrift::protocol::TProtocol* iprot_;
  apache::thrift::protocol::TProtocol* oprot_;
};

class StupaProcessor : virtual public apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<StupaIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (StupaProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*)> processMap_;
  void process_add_document(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_delete_document(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_size(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_search(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
 public:
  StupaProcessor(boost::shared_ptr<StupaIf> iface) :
    iface_(iface) {
    processMap_["add_document"] = &StupaProcessor::process_add_document;
    processMap_["delete_document"] = &StupaProcessor::process_delete_document;
    processMap_["size"] = &StupaProcessor::process_size;
    processMap_["search"] = &StupaProcessor::process_search;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot);
  virtual ~StupaProcessor() {}
};

class StupaMultiface : virtual public StupaIf {
 public:
  StupaMultiface(std::vector<boost::shared_ptr<StupaIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~StupaMultiface() {}
 protected:
  std::vector<boost::shared_ptr<StupaIf> > ifaces_;
  StupaMultiface() {}
  void add(boost::shared_ptr<StupaIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void add_document(const std::string& document_id, const std::vector<std::string> & features) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->add_document(document_id, features);
    }
  }

  void delete_document(const std::string& document_id) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->delete_document(document_id);
    }
  }

  int64_t size() {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->size();
      } else {
        ifaces_[i]->size();
      }
    }
  }

  void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->search(_return, max, query);
        return;
      } else {
        ifaces_[i]->search(_return, max, query);
      }
    }
  }

};



#endif
