/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef StupaThrift_H
#define StupaThrift_H

#include <TProcessor.h>
#include "stupa_types.h"



class StupaThriftIf {
 public:
  virtual ~StupaThriftIf() {}
  virtual void add_document(const std::string& document_id, const std::vector<std::string> & features) = 0;
  virtual void delete_document(const std::string& document_id) = 0;
  virtual int64_t size() = 0;
  virtual void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query) = 0;
  virtual bool save(const std::string& filename) = 0;
  virtual bool load(const std::string& filename) = 0;
};

class StupaThriftNull : virtual public StupaThriftIf {
 public:
  virtual ~StupaThriftNull() {}
  void add_document(const std::string& /* document_id */, const std::vector<std::string> & /* features */) {
    return;
  }
  void delete_document(const std::string& /* document_id */) {
    return;
  }
  int64_t size() {
    int64_t _return = 0;
    return _return;
  }
  void search(std::vector<SearchResult> & /* _return */, const int64_t /* max */, const std::vector<std::string> & /* query */) {
    return;
  }
  bool save(const std::string& /* filename */) {
    bool _return = false;
    return _return;
  }
  bool load(const std::string& /* filename */) {
    bool _return = false;
    return _return;
  }
};

class StupaThrift_add_document_args {
 public:

  StupaThrift_add_document_args() : document_id("") {
  }

  virtual ~StupaThrift_add_document_args() throw() {}

  std::string document_id;
  std::vector<std::string>  features;

  struct __isset {
    __isset() : document_id(false), features(false) {}
    bool document_id;
    bool features;
  } __isset;

  bool operator == (const StupaThrift_add_document_args & rhs) const
  {
    if (!(document_id == rhs.document_id))
      return false;
    if (!(features == rhs.features))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_add_document_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_add_document_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_add_document_pargs {
 public:


  virtual ~StupaThrift_add_document_pargs() throw() {}

  const std::string* document_id;
  const std::vector<std::string> * features;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_add_document_result {
 public:

  StupaThrift_add_document_result() {
  }

  virtual ~StupaThrift_add_document_result() throw() {}


  bool operator == (const StupaThrift_add_document_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StupaThrift_add_document_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_add_document_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_add_document_presult {
 public:


  virtual ~StupaThrift_add_document_presult() throw() {}


  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThrift_delete_document_args {
 public:

  StupaThrift_delete_document_args() : document_id("") {
  }

  virtual ~StupaThrift_delete_document_args() throw() {}

  std::string document_id;

  struct __isset {
    __isset() : document_id(false) {}
    bool document_id;
  } __isset;

  bool operator == (const StupaThrift_delete_document_args & rhs) const
  {
    if (!(document_id == rhs.document_id))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_delete_document_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_delete_document_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_delete_document_pargs {
 public:


  virtual ~StupaThrift_delete_document_pargs() throw() {}

  const std::string* document_id;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_delete_document_result {
 public:

  StupaThrift_delete_document_result() {
  }

  virtual ~StupaThrift_delete_document_result() throw() {}


  bool operator == (const StupaThrift_delete_document_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StupaThrift_delete_document_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_delete_document_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_delete_document_presult {
 public:


  virtual ~StupaThrift_delete_document_presult() throw() {}


  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThrift_size_args {
 public:

  StupaThrift_size_args() {
  }

  virtual ~StupaThrift_size_args() throw() {}


  bool operator == (const StupaThrift_size_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StupaThrift_size_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_size_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_size_pargs {
 public:


  virtual ~StupaThrift_size_pargs() throw() {}


  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_size_result {
 public:

  StupaThrift_size_result() : success(0) {
  }

  virtual ~StupaThrift_size_result() throw() {}

  int64_t success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const StupaThrift_size_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_size_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_size_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_size_presult {
 public:


  virtual ~StupaThrift_size_presult() throw() {}

  int64_t* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThrift_search_args {
 public:

  StupaThrift_search_args() : max(0) {
  }

  virtual ~StupaThrift_search_args() throw() {}

  int64_t max;
  std::vector<std::string>  query;

  struct __isset {
    __isset() : max(false), query(false) {}
    bool max;
    bool query;
  } __isset;

  bool operator == (const StupaThrift_search_args & rhs) const
  {
    if (!(max == rhs.max))
      return false;
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_search_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_search_pargs {
 public:


  virtual ~StupaThrift_search_pargs() throw() {}

  const int64_t* max;
  const std::vector<std::string> * query;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_search_result {
 public:

  StupaThrift_search_result() {
  }

  virtual ~StupaThrift_search_result() throw() {}

  std::vector<SearchResult>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const StupaThrift_search_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_search_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_search_presult {
 public:


  virtual ~StupaThrift_search_presult() throw() {}

  std::vector<SearchResult> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThrift_save_args {
 public:

  StupaThrift_save_args() : filename("") {
  }

  virtual ~StupaThrift_save_args() throw() {}

  std::string filename;

  struct __isset {
    __isset() : filename(false) {}
    bool filename;
  } __isset;

  bool operator == (const StupaThrift_save_args & rhs) const
  {
    if (!(filename == rhs.filename))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_save_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_save_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_save_pargs {
 public:


  virtual ~StupaThrift_save_pargs() throw() {}

  const std::string* filename;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_save_result {
 public:

  StupaThrift_save_result() : success(0) {
  }

  virtual ~StupaThrift_save_result() throw() {}

  bool success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const StupaThrift_save_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_save_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_save_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_save_presult {
 public:


  virtual ~StupaThrift_save_presult() throw() {}

  bool* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThrift_load_args {
 public:

  StupaThrift_load_args() : filename("") {
  }

  virtual ~StupaThrift_load_args() throw() {}

  std::string filename;

  struct __isset {
    __isset() : filename(false) {}
    bool filename;
  } __isset;

  bool operator == (const StupaThrift_load_args & rhs) const
  {
    if (!(filename == rhs.filename))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_load_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_load_args & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_load_pargs {
 public:


  virtual ~StupaThrift_load_pargs() throw() {}

  const std::string* filename;

  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_load_result {
 public:

  StupaThrift_load_result() : success(0) {
  }

  virtual ~StupaThrift_load_result() throw() {}

  bool success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const StupaThrift_load_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StupaThrift_load_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StupaThrift_load_result & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

class StupaThrift_load_presult {
 public:


  virtual ~StupaThrift_load_presult() throw() {}

  bool* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);

};

class StupaThriftClient : virtual public StupaThriftIf {
 public:
  StupaThriftClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  StupaThriftClient(boost::shared_ptr<apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr<apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void add_document(const std::string& document_id, const std::vector<std::string> & features);
  void send_add_document(const std::string& document_id, const std::vector<std::string> & features);
  void recv_add_document();
  void delete_document(const std::string& document_id);
  void send_delete_document(const std::string& document_id);
  void recv_delete_document();
  int64_t size();
  void send_size();
  int64_t recv_size();
  void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query);
  void send_search(const int64_t max, const std::vector<std::string> & query);
  void recv_search(std::vector<SearchResult> & _return);
  bool save(const std::string& filename);
  void send_save(const std::string& filename);
  bool recv_save();
  bool load(const std::string& filename);
  void send_load(const std::string& filename);
  bool recv_load();
 protected:
  boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot_;
  apache::thrift::protocol::TProtocol* iprot_;
  apache::thrift::protocol::TProtocol* oprot_;
};

class StupaThriftProcessor : virtual public apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<StupaThriftIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (StupaThriftProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*)> processMap_;
  void process_add_document(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_delete_document(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_size(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_search(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_save(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
  void process_load(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot);
 public:
  StupaThriftProcessor(boost::shared_ptr<StupaThriftIf> iface) :
    iface_(iface) {
    processMap_["add_document"] = &StupaThriftProcessor::process_add_document;
    processMap_["delete_document"] = &StupaThriftProcessor::process_delete_document;
    processMap_["size"] = &StupaThriftProcessor::process_size;
    processMap_["search"] = &StupaThriftProcessor::process_search;
    processMap_["save"] = &StupaThriftProcessor::process_save;
    processMap_["load"] = &StupaThriftProcessor::process_load;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot);
  virtual ~StupaThriftProcessor() {}
};

class StupaThriftMultiface : virtual public StupaThriftIf {
 public:
  StupaThriftMultiface(std::vector<boost::shared_ptr<StupaThriftIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~StupaThriftMultiface() {}
 protected:
  std::vector<boost::shared_ptr<StupaThriftIf> > ifaces_;
  StupaThriftMultiface() {}
  void add(boost::shared_ptr<StupaThriftIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void add_document(const std::string& document_id, const std::vector<std::string> & features) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->add_document(document_id, features);
    }
  }

  void delete_document(const std::string& document_id) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->delete_document(document_id);
    }
  }

  int64_t size() {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->size();
      } else {
        ifaces_[i]->size();
      }
    }
  }

  void search(std::vector<SearchResult> & _return, const int64_t max, const std::vector<std::string> & query) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->search(_return, max, query);
        return;
      } else {
        ifaces_[i]->search(_return, max, query);
      }
    }
  }

  bool save(const std::string& filename) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->save(filename);
      } else {
        ifaces_[i]->save(filename);
      }
    }
  }

  bool load(const std::string& filename) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->load(filename);
      } else {
        ifaces_[i]->load(filename);
      }
    }
  }

};



#endif
