/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "stupa_constants.h"

namespace stupa { namespace thrift {

const stupaConstants g_stupa_constants;

stupaConstants::stupaConstants() {
}

}} // namespace

